name = "TimeSeries"
uuid = "9e3dc215-6440-5c97-bce1-76c03772f85e"
authors = ["JuliaStats <https://github.com/JuliaStats>"]
version = "0.25.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DelimitedFiles = "1"
DocStringExtensions = "0.8, 0.9"
RecipesBase = "0.5, 0.7, 0.8, 1.0"
Reexport = "1"
Statistics = "1"
Tables = "1"
julia = "1.6"
PrettyTables = "2,3"
IteratorInterfaceExtensions = "1"
TableTraits = "1"
