name = "TimeSeries"
uuid = "9e3dc215-6440-5c97-bce1-76c03772f85e"
authors = ["JuliaStats <https://github.com/JuliaStats>"]
version = "0.22.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DocStringExtensions = "0.8"
MarketData = "0.13"
RecipesBase = "0.5, 0.7, 0.8, 1.0"
Reexport = "1"
Tables = "1"
julia = "1"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
MarketData = "945b72a4-3b13-509d-9b46-1525bb5c06de"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "DataFrames", "MarketData", "Random", "Test"]
